### ISSUE TITLE
Runescape to Discord Message not converting symbols or space

### ISSUE THREAD

**Issue by Lmctruck30** [aeramos/RuneScape-Discord-Chat-Sync#7]
The message if it has a symbol as is > or < is not converting it to that on discord but rather the html code for it &61; into the discord channel

**Comment by aeramos** [comment]
After doing some testing the bot outputs HTML character codes for `<` `>` `&` and it formats the text weirdly for `.

**Comment by Lmctruck30** [comment]
Is there a solution that could fix this issue?

**Comment by aeramos** [comment]
@Lmctruck30 I just pushed a commit that fixes this. It was nothing major, I just had to change the way the bot gets the message (it now gets the nodeValue instead of the innerHTML) and for the backticks I just had to borrow some code from the discord.js API. Thank you for reporting this, I probably wouldn't have found it otherwise.

**Comment by aeramos** [comment]
Fixed in commit 4a8fe3edcee4fd5d3d5d9366c8a2204b36526eda
